name: Backend Release Check

on:
  push:
    branches:
      - master
    paths:
      - 'apps/backend/**'

jobs:
  validate-backend:
    # Matches the label set in docker-compose.yml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Explicitly install Node so you there's no guessing what the container has
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        # Run from the root to link all workspaces
        run: yarn install --frozen-lockfile

      - name: Test Backend
        # Target the specific workspace without needing to 'cd'
        run: yarn workspace backend test