#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run the full type-check to make sure shared changes didn't break the backend
yarn run typecheck

# Run linting and tests only on the files you're committing
npx lint-staged